/*
 * Configuración de comercios para QARTA.
 * El motor no depende de la marca, categorías ni productos de esta demo.
 */
(() => {
  const extra = (id, label, price) => ({ id, label, price });
  const variant = (id, label, priceDelta = 0) => ({ id, label, priceDelta });
  const product = (details) => ({ available: true, featured: false, tags: [], variants: [], extras: [], ...details });

  const sushiDemo = {
    slug: "sushi-demo",
    isDemo: true,
    brand: {
      name: "Nori Lenta",
      shortName: "NL",
      descriptor: "Sushi de estación",
      tagline: "Sushi hecho con tiempo, para comer sin apuro.",
      description: "Una selección de rolls, piezas y combinaciones pensada para compartir o disfrutar de a poco.",
    },
    meta: {
      title: "Nori Lenta · Demo gastronómica | NODO",
      description: "Una experiencia demostrativa de carta digital, pedidos y checkout por WhatsApp.",
      image: "assets/restaurants/sushi-demo/hero-sushi.jpg",
    },
    presentation: {
      skin: "sushi-editorial",
      heroLayout: "plate",
      cardLayout: "image-led",
      density: "airy",
      colors: {
        ink: "#202522",
        paper: "#f4f0e8",
        paperStrong: "#e8e2d5",
        accent: "#65735f",
        accentDeep: "#384837",
        warm: "#bf8b58",
        line: "#d4cdbd",
      },
    },
    contact: {
      whatsapp: "5491130700900",
      locationLabel: "Belgrano · Ciudad de Buenos Aires",
      pickupLabel: "Retiro por Belgrano",
      publicUrl: "https://nododigital.com.ar/demos/gastronomia/?r=sushi-demo",
      instagramUrl: "",
    },
    schedule: [
      { days: "Martes a jueves", hours: "18:30 a 23:00" },
      { days: "Viernes y sábado", hours: "18:30 a 23:30" },
      { days: "Domingo", hours: "18:30 a 22:30" },
    ],
    hero: {
      eyebrow: "CARTA DIGITAL · DEMO",
      title: "Piezas simples, sabores que se quedan.",
      copy: "Una carta clara para elegir con calma, armar tu pedido y continuarlo por WhatsApp.",
      image: "assets/restaurants/sushi-demo/hero-sushi.jpg",
      imageAlt: "Selección de sushi sobre una mesa clara",
      primaryCta: "Ver la carta",
      secondaryCta: "Cómo pedir",
    },
    copy: {
      heroCaption: "Selección de la semana",
      navigation: {
        menu: "Carta",
        promotions: "Para compartir",
        how: "Cómo pedir",
        local: "El local",
      },
      categories: {
        eyebrow: "PARA EMPEZAR",
        title: "Elegí por antojo, no por apuro.",
      },
      menu: {
        eyebrow: "LA CARTA",
        title: "Todo lo que querés pedir.",
        searchPlaceholder: "Buscar una pieza",
        emptySearch: "No encontramos piezas con esa búsqueda.",
        clearSearch: "Limpiar búsqueda",
        productCta: "Elegir",
      },
      how: {
        eyebrow: "SIN COMPLICARLO",
        title: "Tu pedido, en tres pasos.",
        steps: [
          { title: "Elegí lo que te gusta.", copy: "Filtrá, buscá y revisá cada pieza con calma." },
          { title: "Armá tu pedido.", copy: "Elegí variantes y extras antes de sumarlo." },
          { title: "Lo seguimos por WhatsApp.", copy: "Definís retiro o envío y recibís el resumen listo para consultar." },
        ],
      },
      local: {
        eyebrow: "CERCA, A TU RITMO",
        copy: "Podés coordinar retiro o consultar por envío al cerrar el pedido. Los datos son demostrativos.",
        scheduleTitle: "Horarios de referencia",
        qrMissingNote: "QR local preparado para incorporar cuando esté disponible.",
      },
      product: {
        variantsLegend: "Elegí una opción",
        extrasLegend: "¿Querés sumar algo?",
        addCta: "Agregar",
        unavailable: "No disponible",
        featured: "Elegido",
      },
      cart: {
        eyebrow: "TU PEDIDO",
        title: "Una mesa en camino.",
        clearCta: "Vaciar",
        subtotalLabel: "Subtotal",
        emptyTitle: "Todavía no elegiste nada.",
        emptyCopy: "La carta está lista para que armes un pedido a tu ritmo.",
        browseCta: "Ver la carta",
      },
    },
    categories: [
      { id: "combos", label: "Combos", description: "Para elegir y compartir." },
      { id: "rolls", label: "Rolls", description: "Clásicos de la casa." },
      { id: "nigiris", label: "Nigiris", description: "Piezas sin vueltas." },
      { id: "geishas", label: "Geishas", description: "Suaves y frescas." },
      { id: "entradas", label: "Entradas", description: "Para abrir el pedido." },
      { id: "veggie", label: "Veggie", description: "Opciones vegetales." },
      { id: "bebidas", label: "Bebidas", description: "Para acompañar." },
    ],
    promotions: [
      {
        id: "mitad-de-semana",
        active: true,
        startsAt: "2026-01-01",
        endsAt: "2027-01-01",
        eyebrow: "PARA COMPARTIR",
        title: "Dos combinaciones, una mesa más larga.",
        copy: "Pedí dos combos de 24 piezas y sumá una limonada de jengibre sin cargo.",
        note: "Promoción demostrativa. Aplicación a coordinar por WhatsApp.",
        image: "assets/restaurants/sushi-demo/products-combos.jpg",
        imageAlt: "Combinación de sushi servida para compartir",
      },
    ],
    qr: {
      asset: "",
      target: "https://nododigital.com.ar/demos/gastronomia/?r=sushi-demo",
      label: "Link de la carta",
    },
    products: [
      product({ id: "combo-casa", name: "Combo casa", description: "32 piezas para probar rolls frescos y piezas de salmón.", category: "combos", price: 38800, image: "assets/restaurants/sushi-demo/products-combos.jpg", imageAlt: "Combo de sushi variado", featured: true, tags: ["32 piezas", "Para compartir"], variants: [variant("clasico", "Selección clásica"), variant("sin-crudos", "Sin crudos", 1200)], extras: [extra("salsa-teriyaki", "Salsa teriyaki", 700), extra("wasabi", "Wasabi extra", 450)] }),
      product({ id: "combo-dos-orillas", name: "Dos orillas", description: "24 piezas de rolls, geishas y nigiris para una mesa de dos.", category: "combos", price: 30400, image: "assets/restaurants/sushi-demo/products-combos.jpg", imageAlt: "Tabla de sushi para dos personas", featured: true, tags: ["24 piezas", "Para dos"], variants: [variant("clasico", "Selección clásica"), variant("veggie-mixto", "Mitad veggie", 0)], extras: [extra("soja", "Salsa de soja extra", 450), extra("jengibre", "Jengibre extra", 450)] }),
      product({ id: "combo-lento", name: "Combo lento", description: "48 piezas variadas para quedarse un rato más.", category: "combos", price: 56400, image: "assets/restaurants/sushi-demo/products-combos.jpg", imageAlt: "Gran selección de sushi", tags: ["48 piezas", "Para compartir"], variants: [variant("clasico", "Selección clásica"), variant("sin-crudos", "Sin crudos", 1800)], extras: [extra("palitos", "Juego de palitos extra", 250), extra("salsa-teriyaki", "Salsa teriyaki", 700)] }),
      product({ id: "roll-philadelphia", name: "Philadelphia", description: "Salmón, queso crema y palta, envuelto en sésamo.", category: "rolls", price: 12400, image: "assets/restaurants/sushi-demo/products-rolls.jpg", imageAlt: "Roll de salmón y palta", featured: true, tags: ["8 piezas"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 5200)], extras: [extra("soja", "Salsa de soja extra", 450), extra("wasabi", "Wasabi extra", 450)] }),
      product({ id: "roll-acevichado", name: "Acevichado", description: "Langostino crocante, palta y una salsa cítrica suave.", category: "rolls", price: 13900, image: "assets/restaurants/sushi-demo/products-rolls.jpg", imageAlt: "Roll de sushi acevichado", featured: true, tags: ["8 piezas", "Crocante"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 5800)], extras: [extra("salsa-citrica", "Salsa cítrica extra", 650), extra("jengibre", "Jengibre extra", 450)] }),
      product({ id: "roll-spicy-salmon", name: "Spicy salmón", description: "Salmón, verdeo y toque de ají suave.", category: "rolls", price: 13200, image: "assets/restaurants/sushi-demo/products-rolls.jpg", imageAlt: "Roll de salmón con cobertura", tags: ["8 piezas"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 5500)], extras: [extra("spicy", "Salsa spicy extra", 650), extra("soja", "Salsa de soja extra", 450)] }),
      product({ id: "roll-langostino", name: "Langostino crocante", description: "Langostino tempura, pepino y palta.", category: "rolls", price: 13700, image: "assets/restaurants/sushi-demo/products-rolls.jpg", imageAlt: "Roll crocante de langostino", tags: ["8 piezas", "Tempura"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 5700)], extras: [extra("teriyaki", "Salsa teriyaki", 700), extra("salsa-citrica", "Salsa cítrica extra", 650)] }),
      product({ id: "nigiri-salmon", name: "Nigiri de salmón", description: "Salmón fresco sobre arroz tibio.", category: "nigiris", price: 7200, image: "assets/restaurants/sushi-demo/products-nigiris.jpg", imageAlt: "Nigiris de salmón", tags: ["4 piezas"], variants: [variant("4", "4 piezas"), variant("8", "8 piezas", 6800)], extras: [extra("wasabi", "Wasabi extra", 450), extra("jengibre", "Jengibre extra", 450)] }),
      product({ id: "nigiri-pesca-blanca", name: "Nigiri de pesca blanca", description: "Piezas suaves con un toque de lima.", category: "nigiris", price: 6900, image: "assets/restaurants/sushi-demo/products-nigiris.jpg", imageAlt: "Nigiris de pescado blanco", tags: ["4 piezas"], variants: [variant("4", "4 piezas"), variant("8", "8 piezas", 6500)], extras: [extra("ponzu", "Ponzu cítrico", 600), extra("wasabi", "Wasabi extra", 450)] }),
      product({ id: "nigiri-langostino", name: "Nigiri de langostino", description: "Langostino cocido, arroz y sésamo tostado.", category: "nigiris", price: 7400, image: "assets/restaurants/sushi-demo/products-nigiris.jpg", imageAlt: "Nigiris de langostino", tags: ["4 piezas"], variants: [variant("4", "4 piezas"), variant("8", "8 piezas", 7000)], extras: [extra("soja", "Salsa de soja extra", 450)] }),
      product({ id: "geisha-salmon", name: "Geisha de salmón", description: "Salmón, palta y queso crema, con un hilo de teriyaki.", category: "geishas", price: 10800, image: "assets/restaurants/sushi-demo/products-geishas.jpg", imageAlt: "Geishas de salmón", featured: true, tags: ["8 piezas"], variants: [variant("8", "8 piezas")], extras: [extra("teriyaki", "Salsa teriyaki", 700), extra("sesamo", "Sésamo tostado", 350)] }),
      product({ id: "geisha-mango", name: "Geisha de mango", description: "Mango, palta y pepino con una nota cítrica.", category: "geishas", price: 10100, image: "assets/restaurants/sushi-demo/products-geishas.jpg", imageAlt: "Geishas con mango", tags: ["8 piezas", "Vegetariano"], variants: [variant("8", "8 piezas")], extras: [extra("ponzu", "Ponzu cítrico", 600)] }),
      product({ id: "gyozas-verduras", name: "Gyozas de verduras", description: "Seis piezas doradas, servidas con salsa de la casa.", category: "entradas", price: 7900, image: "assets/restaurants/sushi-demo/products-gyozas.jpg", imageAlt: "Gyozas doradas", tags: ["6 piezas", "Vegetariano"], variants: [variant("6", "6 piezas"), variant("10", "10 piezas", 4400)], extras: [extra("salsa-gyoza", "Salsa de la casa", 600)] }),
      product({ id: "ebi-tempura", name: "Ebi tempura", description: "Langostinos crocantes con salsa cítrica.", category: "entradas", price: 8900, image: "assets/restaurants/sushi-demo/products-gyozas.jpg", imageAlt: "Langostinos tempura", tags: ["6 piezas"], variants: [variant("6", "6 piezas")], extras: [extra("salsa-citrica", "Salsa cítrica extra", 650)] }),
      product({ id: "edamame", name: "Edamame", description: "Vainas tibias con sal marina y limón.", category: "entradas", price: 5600, image: "assets/restaurants/sushi-demo/products-gyozas.jpg", imageAlt: "Edamame servido con limón", tags: ["Para compartir"], extras: [extra("picante", "Toque picante", 350)] }),
      product({ id: "veggie-verde", name: "Roll verde", description: "Palta, pepino, zanahoria y sésamo tostado.", category: "veggie", price: 9800, image: "assets/restaurants/sushi-demo/products-veggie.jpg", imageAlt: "Roll vegetariano con palta", tags: ["8 piezas", "Vegetariano"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 4100)], extras: [extra("ponzu", "Ponzu cítrico", 600), extra("sesamo", "Sésamo tostado", 350)] }),
      product({ id: "veggie-hongo", name: "Roll de hongo", description: "Hongos salteados, palta y verdeo fresco.", category: "veggie", price: 10300, image: "assets/restaurants/sushi-demo/products-veggie.jpg", imageAlt: "Roll vegetariano con hongos", tags: ["8 piezas", "Vegetariano"], variants: [variant("8", "8 piezas"), variant("12", "12 piezas", 4300)], extras: [extra("teriyaki", "Salsa teriyaki", 700)] }),
      product({ id: "veggie-inari", name: "Inari vegetal", description: "Tofu frito relleno de arroz, pepino y sésamo.", category: "veggie", price: 8200, image: "assets/restaurants/sushi-demo/products-veggie.jpg", imageAlt: "Inari vegetariano", tags: ["4 piezas", "Vegetariano"], variants: [variant("4", "4 piezas"), variant("8", "8 piezas", 7600)], extras: [extra("ponzu", "Ponzu cítrico", 600)] }),
      product({ id: "limonada-jengibre", name: "Limonada de jengibre", description: "Limonada suave, jengibre y menta.", category: "bebidas", price: 3900, image: "assets/restaurants/sushi-demo/products-bebidas.jpg", imageAlt: "Limonada con jengibre", tags: ["Sin alcohol"], variants: [variant("vaso", "Vaso 500 ml"), variant("jarra", "Jarra para compartir", 4100)] }),
      product({ id: "te-frio", name: "Té verde frío", description: "Té verde, cítricos y un toque de miel.", category: "bebidas", price: 3500, image: "assets/restaurants/sushi-demo/products-bebidas.jpg", imageAlt: "Té verde frío servido con hielo", tags: ["Sin alcohol"], variants: [variant("vaso", "Vaso 500 ml")] }),
      product({ id: "agua-sin-gas", name: "Agua sin gas", description: "Agua mineral fría.", category: "bebidas", price: 2600, image: "assets/restaurants/sushi-demo/products-bebidas.jpg", imageAlt: "Botella de agua", tags: ["500 ml"], variants: [variant("500", "500 ml"), variant("1500", "1,5 L", 1700)] }),
    ],
  };

  const edicionCafe = {
    slug: "edicion-cafe",
    isDemo: true,
    brand: {
      name: "EDICIÓN CAFÉ",
      shortName: "EC",
      descriptor: "Café · papel · ciudad",
      tagline: "Café para leer la ciudad.",
      description: "Una cafetería urbana ficticia para hacer una pausa breve entre una cosa y la otra.",
    },
    meta: {
      title: "EDICIÓN CAFÉ · Demo gastronómica | NODO",
      description: "Una demostración de carta digital para una cafetería urbana con bloques editoriales, carrito y checkout por WhatsApp.",
      image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp",
    },
    presentation: {
      skin: "press",
      heroLayout: "cover",
      cardLayout: "bulletin",
      density: "compact",
      colors: {
        ink: "#22231f",
        paper: "#f3efe5",
        paperStrong: "#e6decf",
        accent: "#9a3d2f",
        accentDeep: "#682f27",
        warm: "#677060",
        line: "#bbb09f",
      },
    },
    contact: {
      whatsapp: "5491130700900",
      locationLabel: "Puesto demo · Ciudad de Buenos Aires",
      pickupLabel: "Retiro demo · Esquina editorial",
      publicUrl: "https://nododigital.com.ar/demos/gastronomia/?r=edicion-cafe",
      instagramUrl: "",
    },
    schedule: [
      { days: "Lunes a viernes", hours: "08:00 a 18:30" },
      { days: "Sábados", hours: "09:00 a 17:00" },
      { days: "Domingos", hours: "10:00 a 14:00" },
    ],
    hero: {
      eyebrow: "PORTADA · CAFÉ, PAPEL Y CIUDAD",
      title: "Café para leer la ciudad.",
      copy: "Una pausa breve, algo para llevar y una idea que puede seguir después.",
      image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp",
      imageAlt: "Café con medialuna servido al aire libre",
      primaryCta: "Ver la carta",
      secondaryCta: "La edición de hoy",
      secondaryTarget: "#edicion",
    },
    copy: {
      heroCaption: "Café · papel · ciudad",
      navigation: {
        cover: "Portada",
        menu: "La carta",
        readings: "Lecturas",
        place: "El puesto",
        local: "Dónde estamos",
      },
      categories: {
        eyebrow: "ELEGÍ TU PAUSA",
        title: "Una carta corta, clara y lista para seguir.",
      },
      menu: {
        eyebrow: "LA CARTA",
        title: "Café, algo rico y un rato propio.",
        searchPlaceholder: "Buscar en la carta",
        emptySearch: "No encontramos nada con esa búsqueda.",
        clearSearch: "Limpiar búsqueda",
        productCta: "Ver opciones",
      },
      how: {
        eyebrow: "PEDIR, SIN DAR VUELTAS",
        title: "Tu pedido, en tres pasos.",
        steps: [
          { title: "Elegí tu pausa.", copy: "Buscá por categoría o revisá cada opción de la carta." },
          { title: "Ajustala a tu gusto.", copy: "Elegí tamaño, leche o algún extra cuando corresponda." },
          { title: "Seguimos por WhatsApp.", copy: "El resumen llega listo para coordinar retiro o envío de demo." },
        ],
      },
      local: {
        eyebrow: "DÓNDE ESTAMOS",
        copy: "Esta ubicación, sus horarios y su WhatsApp son parte de una demostración. La experiencia representa un puesto urbano ficticio preparado para retiro y consultas rápidas.",
        scheduleTitle: "Horarios de demostración",
        qrMissingNote: "Espacio preparado para incorporar el QR local de esta carta.",
      },
      product: {
        variantsLegend: "Elegí una opción",
        extrasLegend: "¿Querés sumar algo?",
        addCta: "Agregar al pedido",
        unavailable: "No disponible",
        featured: "Recomendado",
      },
    },
    editorial: {
      edition: {
        city: "BUENOS AIRES",
        issue: "EDICIÓN Nº 01",
      },
      editionToday: {
        eyebrow: "LA EDICIÓN DE HOY",
        title: "Flat white + medialuna",
        copy: "Una dupla que no necesita corrección.",
        image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp",
        imageAlt: "Flat white y medialuna sobre una mesa exterior",
      },
      readings: [
        {
          id: "cinco-minutos",
          number: "01",
          title: "Cinco minutos sin pantalla",
          copy: "Un café, una página y el margen suficiente para mirar alrededor.",
          image: "assets/restaurants/edicion-cafe/editorial/coffee-newspaper.webp",
          imageAlt: "Café junto a una página impresa",
        },
        {
          id: "esquina",
          number: "02",
          title: "La esquina como lugar de encuentro",
          copy: "La ciudad se cuenta mejor cuando alguien se queda un rato más.",
          image: "assets/restaurants/edicion-cafe/editorial/reading-coffee.webp",
          imageAlt: "Persona leyendo mientras sostiene una taza de café",
        },
        {
          id: "papel",
          number: "03",
          title: "Todavía queda algo en el papel",
          copy: "Una selección breve para hojear antes de seguir el día.",
          image: "assets/restaurants/edicion-cafe/editorial/books-paper.webp",
          imageAlt: "Libros y papel apilados sobre una superficie clara",
        },
      ],
      place: {
        eyebrow: "EL PUESTO",
        title: "Un café rápido no tiene por qué sentirse apurado.",
        copy: "EDICIÓN CAFÉ recupera algo de esa parada urbana que antes tenía el puesto de diarios: mirar una tapa, hojear algo, pedir un café y seguir. Todo el contenido de esta experiencia es ficticio y demostrativo.",
        image: "assets/restaurants/edicion-cafe/editorial/reading-book.webp",
        imageAlt: "Persona leyendo un libro y sosteniendo una taza de café",
      },
    },
    categories: [
      { id: "cafe", label: "Café", description: "Clásicos de barra." },
      { id: "frios", label: "Fríos", description: "Para bajar un cambio." },
      { id: "pasteleria", label: "Pastelería", description: "Algo para acompañar." },
      { id: "salado", label: "Salado", description: "Para quedarse un poco más." },
      { id: "combos", label: "Combos", description: "Una pausa resuelta." },
    ],
    promotions: [
      {
        id: "ultima-hora",
        active: true,
        startsAt: "2026-01-01",
        endsAt: "2027-12-31",
        eyebrow: "ÚLTIMA HORA",
        title: "Flat white + medialuna, una pausa que ya está escrita.",
        copy: "Una combinación de referencia para llegar, pedir y seguir sin perder el ritmo.",
        note: "Promoción demostrativa. La coordinación continúa por WhatsApp.",
        image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp",
        imageAlt: "Flat white y medialuna como combo de cafetería",
      },
      {
        id: "edicion-tarde",
        active: true,
        startsAt: "2026-01-01",
        endsAt: "2027-12-31",
        eyebrow: "EDICIÓN DE LA TARDE",
        title: "Cold brew + cookie para leer entre líneas.",
        copy: "Una segunda promoción demostrativa pensada para mostrar la versatilidad de la carta.",
        note: "Valores y disponibilidad de referencia.",
        image: "assets/restaurants/edicion-cafe/products/coffee-cookies.webp",
        imageAlt: "Café y cookie sobre una mesa",
      },
    ],
    qr: {
      asset: "",
      target: "https://nododigital.com.ar/demos/gastronomia/?r=edicion-cafe#carta",
      label: "Abrir la carta",
    },
    products: [
      product({ id: "espresso", name: "Espresso", description: "Corto, intenso y directo.", category: "cafe", price: 2600, image: "assets/restaurants/edicion-cafe/products/latte-art.webp", imageAlt: "Taza con café espresso", tags: ["Barra"], extras: [extra("shot-extra", "Shot adicional", 900)] }),
      product({ id: "espresso-doble", name: "Espresso doble", description: "Dos shots para cuando la mañana pide más.", category: "cafe", price: 3200, image: "assets/restaurants/edicion-cafe/products/latte-art.webp", imageAlt: "Café servido en taza", tags: ["Doble"], extras: [extra("shot-extra", "Shot adicional", 900)] }),
      product({ id: "cortado", name: "Cortado", description: "Espresso con una nube de leche.", category: "cafe", price: 3300, image: "assets/restaurants/edicion-cafe/products/coffee-serving.webp", imageAlt: "Café con leche servido en taza azul", variants: [variant("entera", "Leche entera"), variant("avena", "Leche de avena", 700)], extras: [extra("shot-extra", "Shot adicional", 900)] }),
      product({ id: "americano", name: "Americano", description: "Espresso largo, simple y sostenido.", category: "cafe", price: 3500, image: "assets/restaurants/edicion-cafe/products/coffee-in-hand.webp", imageAlt: "Persona sosteniendo una taza de café", variants: [variant("chico", "Chico"), variant("grande", "Grande", 700)], extras: [extra("shot-extra", "Shot adicional", 900)] }),
      product({ id: "flat-white", name: "Flat white", description: "Cremoso, breve y protagonista de esta edición.", category: "cafe", price: 4600, image: "assets/restaurants/edicion-cafe/products/coffee-serving.webp", imageAlt: "Flat white servido en taza", featured: true, tags: ["Recomendado"], variants: [variant("entera", "Leche entera"), variant("avena", "Leche de avena", 700)], extras: [extra("shot-extra", "Shot adicional", 900), extra("syrup-vainilla", "Syrup de vainilla", 500)] }),
      product({ id: "cappuccino", name: "Cappuccino", description: "Espuma suave y café con presencia.", category: "cafe", price: 4800, image: "assets/restaurants/edicion-cafe/products/latte-art.webp", imageAlt: "Cappuccino con arte latte", variants: [variant("entera", "Leche entera"), variant("avena", "Leche de avena", 700)], extras: [extra("cacao", "Cacao arriba", 250)] }),
      product({ id: "latte", name: "Latte", description: "Leche texturada, espresso y tiempo para sentarse.", category: "cafe", price: 4900, image: "assets/restaurants/edicion-cafe/products/coffee-in-hand.webp", imageAlt: "Latte servido en taza", variants: [variant("chico", "Chico"), variant("grande", "Grande", 800), variant("avena", "Grande con avena", 1400)], extras: [extra("shot-extra", "Shot adicional", 900), extra("syrup-vainilla", "Syrup de vainilla", 500)] }),
      product({ id: "cold-brew", name: "Cold brew", description: "Café frío de extracción lenta, listo para llevar.", category: "frios", price: 4900, image: "assets/restaurants/edicion-cafe/products/iced-coffee.webp", imageAlt: "Café frío servido en vaso con hielo", featured: true, tags: ["Frío"], variants: [variant("clasico", "Clásico"), variant("con-leche", "Con un toque de leche", 400)], extras: [extra("shot-extra", "Shot adicional", 900)] }),
      product({ id: "iced-latte", name: "Iced latte", description: "Leche, espresso y hielo para una tarde de ciudad.", category: "frios", price: 5200, image: "assets/restaurants/edicion-cafe/products/iced-latte.webp", imageAlt: "Iced latte servido en vaso", variants: [variant("entera", "Leche entera"), variant("avena", "Leche de avena", 700)], extras: [extra("syrup-vainilla", "Syrup de vainilla", 500)] }),
      product({ id: "espresso-tonic", name: "Espresso tonic", description: "Burbujas, café y un final cítrico.", category: "frios", price: 5000, image: "assets/restaurants/edicion-cafe/products/iced-coffee.webp", imageAlt: "Café frío servido en vasos", tags: ["Refrescante"], extras: [extra("rodaja-limon", "Rodaja de limón", 200)] }),
      product({ id: "limonada", name: "Limonada de la casa", description: "Limón, hielo y una pausa sin café.", category: "frios", price: 4000, image: "assets/restaurants/edicion-cafe/products/iced-latte.webp", imageAlt: "Bebida fría servida con hielo", variants: [variant("chica", "Chica"), variant("grande", "Grande", 700)] }),
      product({ id: "medialuna", name: "Medialuna", description: "Manteca, capas y el acompañamiento justo.", category: "pasteleria", price: 1900, image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp", imageAlt: "Medialuna junto a una taza de café", tags: ["Recién horneada"] }),
      product({ id: "medialuna-jyq", name: "Medialuna de jamón y queso", description: "Clásica, salada y lista para salir.", category: "pasteleria", price: 3200, image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp", imageAlt: "Medialuna servida junto a café", tags: ["Salada"] }),
      product({ id: "roll-canela", name: "Roll de canela", description: "Masa suave, canela y glaseado preciso.", category: "pasteleria", price: 4300, image: "assets/restaurants/edicion-cafe/products/cinnamon-roll.webp", imageAlt: "Roll de canela servido en un plato", featured: true, tags: ["Pastelería"], extras: [extra("calentar", "Calentar", 0)] }),
      product({ id: "cookie-chocolate", name: "Cookie de chocolate", description: "Crocante por fuera, blanda en el centro.", category: "pasteleria", price: 3300, image: "assets/restaurants/edicion-cafe/products/coffee-cookies.webp", imageAlt: "Cookie junto a una taza de café", extras: [extra("calentar", "Calentar", 0)] }),
      product({ id: "budin-limon", name: "Budín de limón", description: "Una porción simple para acompañar la lectura.", category: "pasteleria", price: 3400, image: "assets/restaurants/edicion-cafe/products/cinnamon-roll.webp", imageAlt: "Pastelería servida en plato", tags: ["Porción"] }),
      product({ id: "tostado-jyq", name: "Tostado de jamón y queso", description: "Pan dorado, queso fundido y nada de más.", category: "salado", price: 6200, image: "assets/restaurants/edicion-cafe/products/toast-coffee.webp", imageAlt: "Tostado servido junto a café", featured: true, tags: ["Para llevar"], variants: [variant("blanco", "Pan blanco"), variant("integral", "Pan integral", 300)], extras: [extra("queso-extra", "Queso extra", 700)] }),
      product({ id: "croissant-jyq", name: "Croissant JyQ", description: "Manteca, jamón, queso y horno.", category: "salado", price: 6500, image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp", imageAlt: "Croissant servido junto a café", variants: [variant("clasico", "Clásico"), variant("tomate", "Con tomate", 400)] }),
      product({ id: "focaccia-verde", name: "Focaccia verde", description: "Vegetales asados, hojas y queso crema.", category: "salado", price: 6900, image: "assets/restaurants/edicion-cafe/products/toast-coffee.webp", imageAlt: "Sandwich tostado servido en plato", tags: ["Vegetariano"], extras: [extra("queso-extra", "Queso extra", 700)] }),
      product({ id: "toston-hummus", name: "Tostón de hummus", description: "Pan de masa madre, hummus y verdes frescos.", category: "salado", price: 6400, image: "assets/restaurants/edicion-cafe/products/toast-coffee.webp", imageAlt: "Tostada con café", tags: ["Vegetariano"] }),
      product({ id: "combo-cafe-medialuna", name: "Café + medialuna", description: "El clásico para arrancar sin demorarse.", category: "combos", price: 4800, image: "assets/restaurants/edicion-cafe/hero/flat-white-medialuna.webp", imageAlt: "Café y medialuna como desayuno", featured: true, tags: ["Combo"], variants: [variant("cortado", "Con cortado"), variant("americano", "Con americano", 200), variant("latte", "Con latte", 1200)] }),
      product({ id: "combo-flat-roll", name: "Flat white + roll", description: "Café con cuerpo y una pausa dulce.", category: "combos", price: 8200, image: "assets/restaurants/edicion-cafe/products/cinnamon-roll.webp", imageAlt: "Roll de canela junto a café", featured: true, tags: ["Combo"], variants: [variant("entera", "Leche entera"), variant("avena", "Leche de avena", 700)] }),
      product({ id: "combo-tostado-cafe", name: "Tostado + café", description: "Una solución breve para la mitad del día.", category: "combos", price: 8900, image: "assets/restaurants/edicion-cafe/products/toast-coffee.webp", imageAlt: "Tostado y café servidos en una mesa", tags: ["Combo"], variants: [variant("cortado", "Con cortado"), variant("latte", "Con latte", 1300)] }),
    ],
  };

  window.QARTA_CONFIG = {
    defaultRestaurantSlug: "sushi-demo",
    storagePrefix: "nodo_qarta_cart_v1",
    builderStorageKey: "nodo_qarta_builder_v1",
    builderPreviewStorageKey: "nodo_qarta_builder_preview_v1",
  };
  window.QARTA_RESTAURANTS = {
    [sushiDemo.slug]: sushiDemo,
    [edicionCafe.slug]: edicionCafe,
  };
})();
